apiVersion: v1                # Версия API Kubernetes
kind: Pod                     # тип описываемого объекта
metadata:
  name: kubia-manual-v2          # имя объекта(пода)
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: nikolay0110/kubia  # образ для создания контейнера
    name: kubia               # имя контейнера
    ports:
    - containerPort: 8080    # порт, на котором слушает приложение
      protocol: TCP
