apiVersion: v1
kind: ReplicationController       # этот манифест определяет контроллер репликации
metadata:
  name: kubia   # это имя контроллера репликации
spec:
  replicas: 3   # требуемое количество подов модуля
  selector:
    app: kubia  # селектор модулей, определяющий с какими модулями оперирует контроллер replicaSet
  template: # шаблон пода, по нему создаются контроллер репликации понимает какие поды создавать
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: nikolay0110/kubia
          ports:
            - containerPort: 8080
