apiVersion: v1                # Версия API Kubernetes
kind: Pod                     # тип описываемого объекта
metadata:
  name: kubia-manual-gpu      # имя объекта(пода)
spec:
  nodeSelector:
    gpu: "true"               # этот селектор говорит kubernetes запускать этот под только на ноде, у которой есть лейбл gpu=true
  containers:
  - image: nikolay0110/kubia  # образ для создания контейнера
    name: kubia               # имя контейнера
    ports:
    - containerPort: 8080    # порт, на котором слушает приложение
      protocol: TCP
